ductaitran/serwer-management

- backend/.gitignore
- backend/app.js
- backend/package-lock.json
- backend/package.json
- backend/routes/sewers.route.js
> Setup expressjs and mongodb.

- backend/.env
- backend/.gitignore
- backend/app.js
- backend/models/sewer.model.js
- backend/package.json
- backend/routes/sewers.route.js
- backend/routes/users.route.js
> Add basic API (get/post) for sewer.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/sign-in/sign-in.component.jsx
- frontend/src/index.js
- frontend/src/pages/sign-in/sign-in.component.jsx
- add react-router-dom dependecy
- create sign-in page and sign-in component
> Create Sign-in Page

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/custom-button/custom-button.styles.scss
- frontend/src/components/header/header.component.jsx
- frontend/src/components/header/header.styles.scss
- frontend/src/components/sign-up/sign-up.component.jsx
- render sign out button if user logged in
- fix bug in SignUp component
- add tata-js
> Add pseudo check user login in Header component

- backend/controllers/passport.controller.js
- backend/controllers/sewers.controller.js
- backend/controllers/users.controller.js
- backend/middlewares/jsonWebToken.middleware.js
- backend/models/user.model.js
- backend/package-lock.json
- backend/package.json
- backend/routes/general.route.js
- backend/routes/users.route.js
Modify and add hashed password when signup. 
Update sewer list in role schema field when add new sewer.
> Modify and add hashed password when signup.

- backend/controllers/passport.controller.js
- backend/controllers/schedules.controller.js
- backend/controllers/sewers.controller.js
- backend/controllers/users.controller.js
- backend/middlewares/passport.middleware.js
- backend/models/role.model.js
- backend/models/schedule.model.js
- backend/models/sewer.model.js
- backend/routes/general.route.js
- backend/routes/schedules.route.js
- backend/routes/users.route.js
- Change file and module name.
- Add schedule model.
- Propose: delete role model and include role in sewer + user. For example:
user: {
id
name
email
password
role
}
sewer: {
id
name
description
role
}
> Add schedule model, controller and route (GET, POST, DELETE API).

- backend/controllers/passport.controller.js
- backend/controllers/sewers.controller.js
- backend/controllers/users.controller.js
- backend/models/location.model.js
- backend/models/sewer.model.js
- backend/models/user.model.js
- backend/routes/sewers.route.js
- getAll route: response with all sewers in that location.
- If user role is "Admin", response all sewers (no location info).
> Get sewer by location of user.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/card-list/card-list.component.jsx
- frontend/src/components/card-list/card-list.styles.css
- frontend/src/components/card/card.component.jsx
- frontend/src/components/header/header.component.jsx
- frontend/src/components/sign-in/sign-in.component.jsx
- frontend/src/helpers/auth-header.js
- frontend/src/helpers/role.js
- frontend/src/pages/monitor/monitor.component.jsx
- frontend/src/services/sewer.service.js
- frontend/src/utils/privateRoute.js
- add role.js as enum of role
- restrict role to render Monitor Page
- install react-select
- install material-ui
- fix bugs
> Restrict action by roles

- frontend/src/components/card/card.component.jsx
- frontend/src/components/card/card.styles.scss
- frontend/src/components/custom-button/custom-button.styles.scss
- frontend/src/components/schedule/schedule.component.jsx
- frontend/src/components/select-action/select-action.component.jsx
- just a view
- function is not in place
> Add component to set schedule on card

- frontend/src/App.js
- frontend/src/components/card/card.component.jsx
- frontend/src/components/custom-button/custom-button.component.jsx
- frontend/src/components/form-input/form-input.component.jsx
- frontend/src/components/schedule-container/schedule-container.component.jsx
- frontend/src/components/schedule-container/schedule-container.styles.scss
- frontend/src/components/schedule/schedule.component.jsx
- frontend/src/components/select-action/select-action.component.jsx
- frontend/src/components/sign-in/sign-in.component.jsx
- frontend/src/components/sign-up/sign-up.component.jsx
- frontend/src/pages/monitor/monitor.component.jsx
- frontend/src/services/schedule.service.js
- frontend/src/services/sewer.service.js
- create schedule-container component to reuse in control page
- fix bugs
> Complete set schedule feature

- backend/app.js
- backend/controllers/schedules.controller.js
- backend/controllers/sewers.controller.js
- backend/models/sewer.model.js
- backend/utils/mqttFunction.js
> Finish send signal to sewer by schedule feature.

- frontend/src/App.js
- frontend/src/components/schedule-table/schedule-table.component.jsx
- frontend/src/pages/schedule/schedule.component.jsx
- frontend/src/services/schedule.service.js
- create schedule-table component
- show all schedule as table in Schedule page
> Add Schedule page

- frontend/src/components/card-list/card-list.component.jsx
- frontend/src/components/card/card.component.jsx
- frontend/src/components/search-box/search-box.component.jsx
- frontend/src/pages/monitor/monitor.component.jsx
- Search sewer by location in Monitor page
> Add search feature

- frontend/src/components/card/card.component.jsx
- frontend/src/components/schedule-table/schedule-table.component.jsx
- frontend/src/components/search-box/search-box.component.jsx
- frontend/src/pages/monitor/monitor.component.jsx
- frontend/src/pages/schedule/schedule.component.jsx
- frontend/src/services/sewer.service.js
- fix bugs
- modify search box on Monitor page
> Modify Schedule page

- backend/controllers/sewers.controller.js
> Finish sewer add and delete API.

- frontend/src/App.js
- frontend/src/components/card/card.component.jsx
- frontend/src/components/schedule-table/schedule-table.component.jsx
- frontend/src/pages/control/control.component.jsx
- frontend/src/pages/monitor/monitor.component.jsx
- frontend/src/pages/schedule/schedule.component.jsx
- frontend/src/services/schedule.service.js
- Add feature to remove single schedule
- Create control page to control sewer and perform actions on schedule
- todo: modify get schedule data base on response schema changes
> Complete schedule feature

- backend/controllers/schedules.controller.js
- backend/controllers/sewers.controller.js
- backend/controllers/users.controller.js
- backend/models/schedule.model.js
- backend/routes/sewers.route.js
- backend/utils/mqttFunction.js
- Response data from schedule API now have sewer information.
> Upgrade schedule getAll function.

- frontend/src/pages/control/control.component.jsx
- layout
- fix bug on get schedule
> Layout control page

- frontend/src/App.js
- frontend/src/components/schedule-add/schedule-add.component.jsx
- frontend/src/components/schedule-add/schedule-add.styles.scss
- frontend/src/components/search-box/search-box.styles.scss
- frontend/src/components/sewer-add/sewer-add.component.jsx
- frontend/src/components/sewer-add/sewer-add.styles.scss
- frontend/src/components/sign-up/sign-up.component.jsx
- frontend/src/components/user-add/user-add.component.jsx
- frontend/src/components/user-add/user-add.styles.scss
- frontend/src/pages/admin/admin.component.jsx
- frontend/src/pages/monitor/monitor.component.jsx
- frontend/src/services/location.service.js
- frontend/src/services/user.service.js
- add user, add sewer, add schedule
> Admin page

- frontend/src/components/sewer-edit/sewer-edit.component.jsx
- frontend/src/components/sewer-table/sewer-table.component.jsx
- frontend/src/components/sewer-table/sewer-table.styles.scss
- frontend/src/pages/admin/admin.component.jsx
- frontend/src/pages/control/control.component.jsx
- frontend/src/services/sewer.service.js
- done on admin features
- improve UI in control page
> Complete Admin feature
